apiVersion: v1
kind: Service
metadata:
  name: store-server-service
  namespace: store
spec:
  selector:
    app: demo-store-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
