apiVersion: v1
kind: Secret
metadata:
  name: demo-store-secret
  namespace: store
stringData:
  PORT: "5000"
  JWT_SECRET: "secret"
  BASE_URL_ERP: "http://a4172b64968904b5982f9ca31f389a84-1576877609.eu-central-1.elb.amazonaws.com/erp/api"
  MONGO_CONNECTION_URI: "mongodb://root:1234@my-mongodb.store/admin"
  BASE_URL_OSM: "http://a4172b64968904b5982f9ca31f389a84-1576877609.eu-central-1.elb.amazonaws.com/oms/api"
  BASE_URL_BANNERS: "http://a4172b64968904b5982f9ca31f389a84-1576877609.eu-central-1.elb.amazonaws.com/banner/api"
  SECRET: "mySecretKey"